[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
